# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='predict.proto',
  package='predict',
  syntax='proto3',
  serialized_options=b'\n\036com.distiya.fxscrapper.predictB\021FxPredictProtocolP\001\242\002\003FXP',
  serialized_pb=b'\n\rpredict.proto\x12\x07predict\"@\n\x06\x43\x61ndle\x12\x0c\n\x04open\x18\x01 \x01(\x01\x12\r\n\x05\x63lose\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\"@\n\x0cPredictBatch\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12 \n\x07\x63\x61ndles\x18\x02 \x03(\x0b\x32\x0f.predict.Candle\"c\n\x1aPredictBatchForGranularity\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x13\n\x0bgranularity\x18\x02 \x01(\t\x12 \n\x07\x63\x61ndles\x18\x03 \x03(\x0b\x32\x0f.predict.Candle\"^\n\x1fMultiPredictBatchForGranularity\x12\x13\n\x0bgranularity\x18\x01 \x01(\t\x12&\n\x07\x62\x61tches\x18\x02 \x03(\x0b\x32\x15.predict.PredictBatch\"E\n\x0fPredictedCandle\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\"\n\tpredicted\x18\x02 \x01(\x0b\x32\x0f.predict.Candle\"h\n\x1dPredictedCandleForGranularity\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x13\n\x0bgranularity\x18\x02 \x01(\t\x12\"\n\tpredicted\x18\x03 \x01(\x0b\x32\x0f.predict.Candle\"d\n\"MultiPredictedCandleForGranularity\x12\x13\n\x0bgranularity\x18\x01 \x01(\t\x12)\n\x07\x63\x61ndles\x18\x02 \x03(\x0b\x32\x18.predict.PredictedCandle2}\n\tFxPredict\x12p\n\x15getPredictionForBatch\x12(.predict.MultiPredictBatchForGranularity\x1a+.predict.MultiPredictedCandleForGranularity\"\x00\x42;\n\x1e\x63om.distiya.fxscrapper.predictB\x11\x46xPredictProtocolP\x01\xa2\x02\x03\x46XPb\x06proto3'
)




_CANDLE = _descriptor.Descriptor(
  name='Candle',
  full_name='predict.Candle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='open', full_name='predict.Candle.open', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close', full_name='predict.Candle.close', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high', full_name='predict.Candle.high', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low', full_name='predict.Candle.low', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=90,
)


_PREDICTBATCH = _descriptor.Descriptor(
  name='PredictBatch',
  full_name='predict.PredictBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticker', full_name='predict.PredictBatch.ticker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='candles', full_name='predict.PredictBatch.candles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=156,
)


_PREDICTBATCHFORGRANULARITY = _descriptor.Descriptor(
  name='PredictBatchForGranularity',
  full_name='predict.PredictBatchForGranularity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticker', full_name='predict.PredictBatchForGranularity.ticker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='granularity', full_name='predict.PredictBatchForGranularity.granularity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='candles', full_name='predict.PredictBatchForGranularity.candles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=257,
)


_MULTIPREDICTBATCHFORGRANULARITY = _descriptor.Descriptor(
  name='MultiPredictBatchForGranularity',
  full_name='predict.MultiPredictBatchForGranularity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='granularity', full_name='predict.MultiPredictBatchForGranularity.granularity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batches', full_name='predict.MultiPredictBatchForGranularity.batches', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=353,
)


_PREDICTEDCANDLE = _descriptor.Descriptor(
  name='PredictedCandle',
  full_name='predict.PredictedCandle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticker', full_name='predict.PredictedCandle.ticker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predicted', full_name='predict.PredictedCandle.predicted', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=424,
)


_PREDICTEDCANDLEFORGRANULARITY = _descriptor.Descriptor(
  name='PredictedCandleForGranularity',
  full_name='predict.PredictedCandleForGranularity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticker', full_name='predict.PredictedCandleForGranularity.ticker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='granularity', full_name='predict.PredictedCandleForGranularity.granularity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predicted', full_name='predict.PredictedCandleForGranularity.predicted', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=530,
)


_MULTIPREDICTEDCANDLEFORGRANULARITY = _descriptor.Descriptor(
  name='MultiPredictedCandleForGranularity',
  full_name='predict.MultiPredictedCandleForGranularity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='granularity', full_name='predict.MultiPredictedCandleForGranularity.granularity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='candles', full_name='predict.MultiPredictedCandleForGranularity.candles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=632,
)

_PREDICTBATCH.fields_by_name['candles'].message_type = _CANDLE
_PREDICTBATCHFORGRANULARITY.fields_by_name['candles'].message_type = _CANDLE
_MULTIPREDICTBATCHFORGRANULARITY.fields_by_name['batches'].message_type = _PREDICTBATCH
_PREDICTEDCANDLE.fields_by_name['predicted'].message_type = _CANDLE
_PREDICTEDCANDLEFORGRANULARITY.fields_by_name['predicted'].message_type = _CANDLE
_MULTIPREDICTEDCANDLEFORGRANULARITY.fields_by_name['candles'].message_type = _PREDICTEDCANDLE
DESCRIPTOR.message_types_by_name['Candle'] = _CANDLE
DESCRIPTOR.message_types_by_name['PredictBatch'] = _PREDICTBATCH
DESCRIPTOR.message_types_by_name['PredictBatchForGranularity'] = _PREDICTBATCHFORGRANULARITY
DESCRIPTOR.message_types_by_name['MultiPredictBatchForGranularity'] = _MULTIPREDICTBATCHFORGRANULARITY
DESCRIPTOR.message_types_by_name['PredictedCandle'] = _PREDICTEDCANDLE
DESCRIPTOR.message_types_by_name['PredictedCandleForGranularity'] = _PREDICTEDCANDLEFORGRANULARITY
DESCRIPTOR.message_types_by_name['MultiPredictedCandleForGranularity'] = _MULTIPREDICTEDCANDLEFORGRANULARITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Candle = _reflection.GeneratedProtocolMessageType('Candle', (_message.Message,), {
  'DESCRIPTOR' : _CANDLE,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:predict.Candle)
  })
_sym_db.RegisterMessage(Candle)

PredictBatch = _reflection.GeneratedProtocolMessageType('PredictBatch', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTBATCH,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:predict.PredictBatch)
  })
_sym_db.RegisterMessage(PredictBatch)

PredictBatchForGranularity = _reflection.GeneratedProtocolMessageType('PredictBatchForGranularity', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTBATCHFORGRANULARITY,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:predict.PredictBatchForGranularity)
  })
_sym_db.RegisterMessage(PredictBatchForGranularity)

MultiPredictBatchForGranularity = _reflection.GeneratedProtocolMessageType('MultiPredictBatchForGranularity', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPREDICTBATCHFORGRANULARITY,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:predict.MultiPredictBatchForGranularity)
  })
_sym_db.RegisterMessage(MultiPredictBatchForGranularity)

PredictedCandle = _reflection.GeneratedProtocolMessageType('PredictedCandle', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTEDCANDLE,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:predict.PredictedCandle)
  })
_sym_db.RegisterMessage(PredictedCandle)

PredictedCandleForGranularity = _reflection.GeneratedProtocolMessageType('PredictedCandleForGranularity', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTEDCANDLEFORGRANULARITY,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:predict.PredictedCandleForGranularity)
  })
_sym_db.RegisterMessage(PredictedCandleForGranularity)

MultiPredictedCandleForGranularity = _reflection.GeneratedProtocolMessageType('MultiPredictedCandleForGranularity', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPREDICTEDCANDLEFORGRANULARITY,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:predict.MultiPredictedCandleForGranularity)
  })
_sym_db.RegisterMessage(MultiPredictedCandleForGranularity)


DESCRIPTOR._options = None

_FXPREDICT = _descriptor.ServiceDescriptor(
  name='FxPredict',
  full_name='predict.FxPredict',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=634,
  serialized_end=759,
  methods=[
  _descriptor.MethodDescriptor(
    name='getPredictionForBatch',
    full_name='predict.FxPredict.getPredictionForBatch',
    index=0,
    containing_service=None,
    input_type=_MULTIPREDICTBATCHFORGRANULARITY,
    output_type=_MULTIPREDICTEDCANDLEFORGRANULARITY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FXPREDICT)

DESCRIPTOR.services_by_name['FxPredict'] = _FXPREDICT

# @@protoc_insertion_point(module_scope)
